class Province {
  static final address = {
    'An Giang': [
      'Châu Đốc',
      'Châu Phú',
      'Tân Châu',
      'Phú Tân',
      'Chợ Mới',
      'Thoại Sơn',
      'Tri Tôn',
      'Tịnh Biên',
      'An Phú',
      'Châu Thành',
    ],
    'Bà Rịa - Vũng Tàu': [
      'Vũng Tàu',
      'Bà Rịa',
      'Phú Mỹ',
      'Châu Đức',
      'Xuyên Mộc',
      'Long Điền',
      'Đất Đỏ',
      'Côn Đảo',
    ],
    'Bạc Liêu': [
      'Bạc Liêu',
      'Vĩnh Lợi',
      'Hồng Dân',
      'Giá Rai',
      'Phước Long',
      'Đông Hải',
      'Hoà Bình',
    ],
    'Bắc Kạn': [
      'Bắc Kạn',
      'Chợ Đồn',
      'Bạch Thông',
      'Na Rì',
      'Ngân Sơn',
      'Ba Bể',
      'Pác Nặm',
    ],
    'Bắc Giang': [
      'Bắc Giang',
      'Yên Thế',
      'Tân Yên',
      'Lạng Giang',
      'Lục Nam',
      'Lục Ngạn',
      'Sơn Động',
      'Yên Dũng',
      'Việt Yên',
      'Hiệp Hòa',
    ],
    'Bắc Ninh': [
      'Bắc Ninh',
      'Yên Phong',
      'Quế Võ',
      'Tiên Du',
      'Từ Sơn',
      'Thuận Thành',
      'Gia Bình',
      'Lương Tài',
    ],
    'Bến Tre': [
      'Bến Tre',
      'Châu Thành',
      'Chợ Lách',
      'Mỏ Cày Bắc',
      'Giồng Trôm',
      'Bình Đại',
      'Ba Tri',
      'Thạnh Phú',
      'Mỏ Cày Nam',
    ],
    'Bình Dương': [
      'Thủ Dầu Một',
      'Bàu Bàng',
      'Dầu Tiếng',
      'Bến Cát',
      'Phú Giáo',
      'Tân Uyên',
      'Dĩ An',
      'Thuận An',
      'Bắc Tân Uyên',
    ],
    'Bình Định': [
      'Quy Nhơn',
      'An Nhơn',
      'Tuy Phước',
      'Vân Canh',
      'Phù Cát',
      'Vĩnh Thạnh',
      'Hòa Vang',
      'Tây Sơn',
      'Phù Mỹ',
      'An Lão',
      'Hoài Nhơn',
    ],
    'Bình Phước': [
      'Đồng Xoài',
      'Bình Long',
      'Phước Long',
      'Bù Gia Mập',
      'Lộc Ninh',
      'Bù Đốp',
      'Hớn Quản',
      'Đồng Phú',
      'Chơn Thành',
      'Phú Riềng',
    ],
    'Bình Thuận': [
      'Phan Thiết',
      'La Gi',
      'Tuy Phong',
      'Bắc Bình',
      'Hàm Thuận Bắc',
      'Hàm Thuận Nam',
      'Hàm Tân',
      'Phú Quý',
    ],
    'Cà Mau': [
      'Cà Mau',
      'U Minh',
      'Thới Bình',
      'Trần Văn Thời',
      'Cái Nước',
      'Đầm Dơi',
      'Năm Căn',
      'Phú Tân',
      'Ngọc Hiển',
    ],
    'Cao Bằng': [
      'Cao Bằng',
      'Bảo Lạc',
      'Thạch An',
      'Hà Quảng',
      'Trùng Khánh',
      'Nguyên Bình',
      'Hoà An',
      'Quảng Uyên',
      'Trà Lĩnh',
      'Thạnh Hóa',
      'Hạ Lang',
      'Bảo Lâm',
      'Phục Hoà',
    ],
    'Cần Thơ': [
      'Ninh Kiều',
      'Ô Môn',
      'Bình Thuỷ',
      'Cái Răng',
      'Thốt Nốt',
      'Vĩnh Thạnh',
      'Cờ Đỏ',
      'Phong Điền',
      'Thới Lai',
    ],
    'Đà Nẵng': [
      'Hải Châu',
      'Thanh Khê',
      'Sơn Trà',
      'Ngũ Hành Sơn',
      'Liên Chiểu',
      'Cẩm Lệ',
      'Hòa Vang',
    ],
    'Đắk Lắk': [
      'Buôn Ma Thuột',
      'Buôn Hồ',
      'Ea Hleo',
      'Ea Súp',
      'Krông Buk',
      'Krông Năng',
      'Ea Kar',
      "M'Đrắk",
      'Krông Bông',
      'Krông Pắc',
      'Krông A Na',
      'Lắk',
      "Cư M'gar",
    ],
    'Đắk Nông': [
      'Gia Nghĩa',
      'Đắk Glong',
      'Cư Jút',
      'Đắk Mil',
      'Krông Nô',
      'Đắk Song',
      "Đắk R'Lấp",
      'Tuy Đức',
    ],
    'Điện Biên': [
      'Điện Biên Phủ',
      'Mường Lay',
      'Mường Nhé',
      'Mường Chà',
      'Tủa Chùa',
      'Tuần Giáo',
      'Điện Biên',
      'Điện Biên Đông',
      'Mường Ảng',
    ],
    'Đồng Nai': [
      'Biên Hòa',
      'Vĩnh Cửu',
      'Tân Phú',
      'Định Quán',
      'Long Khánh',
      'Xuân Lộc',
      'Long Thành',
      'Nhơn Trạch',
      'Trảng Bom',
      'Cẩm Mỹ',
      'Thống Nhất',
    ],
    'Đồng Tháp': [
      'Cao Lãnh',
      'Sa Đéc',
      'Hồng Ngự',
      'Lai Vung',
      'Tam Nông',
      'Tháp Mười',
      'Cao Lãnh',
      'Tháp Mười',
      'Tân Hồng',
      'Hồng Ngự',
    ],
    'Gia Lai': [
      'Pleiku',
      'An Khê',
      'Ayun Pa',
      'Kbang',
      'Đak Đoa',
      'Chư Păh',
      'Chư Prông',
      'Chư Sê',
      'Đức Cơ',
      'Ia Grai',
      'Ia Pa',
      'KBang',
      'Kông Chro',
      'Krông Pa',
      'Mang Yang',
      'Phú Thiện',
      'Pleiku',
    ],
    'Hà Giang': [
      'Hà Giang',
      'Đồng Văn',
      'Mèo Vạc',
      'Yên Minh',
      'Quản Bạ',
      'Vị Xuyên',
      'Bắc Mê',
      'Hoàng Su Phì',
      'Xín Mần',
      'Bắc Quang',
      'Quang Bình',
    ],
    'Hà Nam': [
      'Phủ Lý',
      'Duy Tiên',
      'Kim Bảng',
      'Thanh Liêm',
      'Bình Lục',
      'Lý Nhân',
    ],
    'Hà Nội': [
      'Ba Đình',
      'Hoàn Kiếm',
      'Tây Hồ',
      'Long Biên',
      'Cầu Giấy',
      'Đống Đa',
      'Hai Bà Trưng',
      'Hoàng Mai',
      'Thanh Xuân',
      'Sóc Sơn',
      'Đông Anh',
      'Gia Lâm',
      'Nam Từ Liêm',
      'Thanh Trì',
      'Bắc Từ Liêm',
      'Mê Linh',
      'Hà Đông',
      'Sơn Tây',
      'Ba Vì',
      'Phúc Thọ',
      'Đan Phượng',
      'Hoài Đức',
      'Quốc Oai',
      'Thạch Thất',
      'Chương Mỹ',
      'Thanh Oai',
      'Thường Tín',
      'Phú Xuyên',
      'Ứng Hòa',
      'Mỹ Đức',
    ],
    'Hà Tĩnh': [
      'Hà Tĩnh',
      'Hồng Lĩnh',
      'Hương Sơn',
      'Hương Khê',
      'Vũ Quang',
      'Can Lộc',
      'Đức Thọ',
      'Lộc Hà',
      'Nghi Xuân',
      'Cẩm Xuyên',
      'Kỳ Anh',
    ],
    'Hải Dương': [
      'Hải Dương',
      'Chí Linh',
      'Nam Sách',
      'Kinh Môn',
      'Kim Thành',
      'Thanh Hà',
      'Cẩm Giàng',
      'Bình Giang',
      'Gia Lộc',
      'Tứ Kỳ',
      'Ninh Giang',
      'Thanh Miện',
    ],
    'Hải Phòng': [
      'Hồng Bàng',
      'Ngô Quyền',
      'Lê Chân',
      'Hải An',
      'Kiến An',
      'Đồ Sơn',
      'Dương Kinh',
      'An Dương',
      'An Lão',
      'Kiến Thuỵ',
      'Tiên Lãng',
      'Vĩnh Bảo',
      'Cát Hải',
      'Bạch Long Vĩ',
    ],
    'Hậu Giang': [
      'Vị Thanh',
      'Ngã Bảy',
      'Châu Thành A',
      'Long Mỹ',
      'Phụng Hiệp',
      'Vị Thuỷ',
      'Long Mỹ',
    ],
    'Hòa Bình': [
      'Hòa Bình',
      'Đà Bắc',
      'Lương Sơn',
      'Kim Bôi',
      'Cao Phong',
      'Tân Lạc',
      'Lạc Sơn',
      'Kỳ Sơn',
      'Lạc Thủy',
      'Yên Thủy',
      'Cẩm Thủy',
      'Lương Sơn',
    ],
    'Hưng Yên': [
      'Hưng Yên',
      'Văn Lâm',
      'Văn Giang',
      'Yên Mỹ',
      'Mỹ Hào',
      'Ân Thi',
      'Khoái Châu',
      'Kim Động',
      'Tiên Lữ',
      'Phù Cừ',
    ],
    'Khánh Hòa': [
      'Nha Trang',
      'Cam Ranh',
      'Cam Lâm',
      'Vạn Ninh',
      'Ninh Hòa',
      'Khánh Vĩnh',
      'Diên Khánh',
      'Khánh Sơn',
      'Trường Sa',
    ],
    'Kiên Giang': [
      'Rạch Giá',
      'Hà Tiên',
      'Kiên Lương',
      'Hòn Đất',
      'Tân Hiệp',
      'Châu Thành',
      'Gò Quao',
      'An Biên',
      'An Minh',
      'Vĩnh Thuận',
      'Phú Quốc',
      'Kiên Hải',
      'U Minh Thượng',
      'Giồng Riềng',
      'Gò Quao',
      'Giang Thành',
      'Hòn Đất',
      'Kiên Lương',
      'Tân Hiệp',
    ],
    'Kon Tum': [
      'Kon Tum',
      'Đắk Glei',
      'Ngọc Hồi',
      'Đắk Tô',
      'Kon Plông',
      'Kon Rẫy',
      'Đắk Hà',
      'Sa Thầy',
      'Tu Mơ Rông',
    ],
    'Lai Châu': [
      'Lai Châu',
      'Tam Đường',
      'Mường Tè',
      'Sìn Hồ',
      'Phong Thổ',
      'Than Uyên',
      'Tân Uyên',
      'Nậm Nhùn',
    ],
    'Lâm Đồng': [
      'Đà Lạt',
      'Bảo Lộc',
      'Đức Trọng',
      'Đam Rông',
      'Lạc Dương',
      'Lâm Hà',
      'Đơn Dương',
      'Di Linh',
      'Đạ Huoai',
      'Đạ Tẻh',
      'Cát Tiên',
      'Lộc Thắng',
    ],
    'Lạng Sơn': [
      'Lạng Sơn',
      'Tràng Định',
      'Bình Gia',
      'Văn Lãng',
      'Bắc Sơn',
      'Văn Quan',
      'Cao Lộc',
      'Văn Minh',
      'Hữu Lũng',
      'Chi Lăng',
      'Lộc Bình',
      'Đình Lập',
    ],
    'Lào Cai': [
      'Lào Cai',
      'Bát Xát',
      'Mường Khương',
      'Si Ma Cai',
      'Bắc Hà',
      'Bảo Thắng',
      'Bảo Yên',
      'Sa Pa',
      'Văn Bàn',
    ],
    'Long An': [
      'Tân An',
      'Kiến Tường',
      'Tân Hưng',
      'Vĩnh Hưng',
      'Mộc Hóa',
      'Tân Thạnh',
      'Thạnh Hóa',
      'Đức Huệ',
      'Đức Hòa',
      'Bến Lức',
      'Thủ Thừa',
      'Châu Thành',
      'Tân Trụ',
      'Cần Đước',
      'Cần Giuộc',
    ],
    'Nam Định': [
      'Nam Định',
      'Mỹ Lộc',
      'Vụ Bản',
      'Ý Yên',
      'Nghĩa Hưng',
      'Nam Trực',
      'Trực Ninh',
      'Xuân Trường',
      'Giao Thủy',
      'Hải Hậu',
    ],
    'Nghệ An': [
      'Vinh',
      'Cửa Lò',
      'Thái Hoà',
      'Quế Phong',
      'Quỳ Châu',
      'Kỳ Sơn',
      'Tương Dương',
      'Nghĩa Đàn',
      'Quỳ Hợp',
      'Quỳnh Lưu',
      'Con Cuông',
      'Tân Kỳ',
      'Anh Sơn',
      'Diễn Châu',
      'Yên Thành',
      'Đô Lương',
      'Thanh Chương',
      'Nghi Lộc',
      'Nam Đàn',
      'Hưng Nguyên',
    ],
    'Ninh Bình': [
      'Ninh Bình',
      'Tam Điệp',
      'Nho Quan',
      'Gia Viễn',
      'Hoa Lư',
      'Yên Khánh',
      'Kim Sơn',
      'Yên Mô',
    ],
    'Ninh Thuận': [
      'Phan Rang-Tháp Chàm',
      'Ninh Hải',
      'Ninh Phước',
      'Bác Ái',
      'Thuận Bắc',
      'Thuận Nam',
    ],
    'Phú Thọ': [
      'Việt Trì',
      'Phú Thọ',
      'Đoan Hùng',
      'Hạ Hoà',
      'Thanh Ba',
      'Phù Ninh',
      'Yên Lập',
      'Cẩm Khê',
      'Tam Nông',
      'Lâm Thao',
      'Thanh Sơn',
      'Thanh Thuỷ',
      'Tân Sơn',
    ],
    'Phú Yên': [
      'Tuy Hòa',
      'Sông Cầu',
      'Đồng Xuân',
      'Sơn Hòa',
      'Tuy An',
      'Sông Hinh',
      'Đông Hòa',
      'Phú Hòa',
    ],
    'Quảng Bình': [
      'Đồng Hới',
      'Tuyên Hóa',
      'Minh Hoá',
      'Quảng Trạch',
      'Bố Trạch',
      'Quảng Ninh',
      'Lệ Thủy',
      'Ba Đồn',
    ],
    'Quảng Nam': [
      'Hội An',
      'Tam Kỳ',
      'Điện Bàn',
      'Duy Xuyên',
      'Đại Lộc',
      'Quế Sơn',
      'Hiệp Đức',
      'Thăng Bình',
      'Núi Thành',
      'Tiên Phước',
      'Bắc Trà My',
      'Nam Trà My',
      'Phước Sơn',
      'Nam Giang',
      'Duy Xuyên',
      'Tây Giang',
      'Đông Giang',
      'Quế Sơn',
      'Nam Trà My',
    ],
    'Quảng Ngãi': [
      'Quảng Ngãi',
      'Quảng Tây',
      'Tây Trà',
      'Sơn Tịnh',
      'Tư Nghĩa',
      'Sơn Hà',
      'Sơn Tây',
      'Minh Long',
      'Nghĩa Hành',
      'Mộ Đức',
      'Đức Phổ',
      'Ba Tơ',
      'Trà Bồng',
      'Lý Sơn',
    ],
    'Quảng Ninh': [
      'Hạ Long',
      'Móng Cái',
      'Cẩm Phả',
      'Uông Bí',
      'Đông Triều',
      'Quảng Yên',
      'Cô Tô',
      'Tiên Yên',
      'Ba Chẽ',
      'Hoành Bồ',
      'Đầm Hà',
      'Vân Đồn',
    ],
    'Quảng Trị': [
      'Đông Hà',
      'Quảng Trị',
      'Vĩnh Linh',
      'Hướng Hóa',
      'Gio Linh',
      'Đa Krông',
      'Cam Lộ',
      'Triệu Phong',
      'Hải Lăng',
      'Cồn Cỏ',
    ],
    'Sóc Trăng': [
      'Sóc Trăng',
      'Châu Thành',
      'Kế Sách',
      'Mỹ Tú',
      'Long Phú',
      'Cù Lao Dung',
      'Mỹ Xuyên',
      'Ngã Năm',
      'Thạnh Trị',
      'Vĩnh Châu',
      'Trần Đề',
    ],
    'Sơn La': [
      'Sơn La',
      'Quỳnh Nhai',
      'Mường La',
      'Thuận Châu',
      'Phù Yên',
      'Bắc Yên',
      'Mai Sơn',
      'Sông Mã',
      'Yên Châu',
      'Mộc Châu',
      'Sốp Cộp',
      'Vân Hồ',
    ],
    'Tây Ninh': [
      'Tây Ninh',
      'Tân Biên',
      'Tân Châu',
      'Dương Minh Châu',
      'Châu Thành',
      'Hòa Thành',
      'Gò Dầu',
      'Bến Cầu',
      'Trảng Bàng',
    ],
    'Thái Bình': [
      'Thái Bình',
      'Thái Thụy',
      'Quỳnh Phụ',
      'Hưng Hà',
      'Đông Hưng',
      'Vũ Thư',
      'Kiến Xương',
      'Tiền Hải',
      'Vụ Bản',
    ],
    'Thái Nguyên': [
      'Thái Nguyên',
      'Sông Công',
      'Định Hoá',
      'Võ Nhai',
      'Đại Từ',
      'Phú Lương',
      'Đồng Hỷ',
      'Đại Đồng',
      'Phổ Yên',
    ],
    'Thanh Hóa': [
      'Thanh Hóa',
      'Bỉm Sơn',
      'Sầm Sơn',
      'Quảng Xương',
      'Hà Trung',
      'Vĩnh Lộc',
      'Yên Định',
      'Thiệu Hóa',
      'Hoằng Hóa',
      'Hậu Lộc',
      'Nga Sơn',
      'Như Thanh',
      'Như Xuân',
      'Lang Chánh',
      'Ngọc Lặc',
      'Quan Hóa',
      'Quan Sơn',
      'Mường Lát',
      'Bá Thước',
      'Cẩm Thủy',
      'Thạch Thành',
      'Vĩnh Thành',
      'Thọ Xuân',
      'Thường Xuân',
      'Tĩnh Gia',
    ],
    'Thừa Thiên Huế': [
      'Huế',
      'Phong Điền',
      'Quảng Điền',
      'Phú Vang',
      'Hương Thủy',
      'Hương Trà',
      'A Lưới',
      'Phú Lộc',
      'Nam Đông',
    ],
    'Tiền Giang': [
      'Mỹ Tho',
      'Cái Bè',
      'Cai Lậy',
      'Châu Thành',
      'Gò Công',
      'Gò Công Đông',
      'Gò Công Tây',
      'Tân Phước',
      'Cai Lậy',
    ],
    'TP. Hồ Chí Minh': [
      'Quận 1',
      'Quận 2',
      'Quận 3',
      'Quận 4',
      'Quận 5',
      'Quận 6',
      'Quận 7',
      'Quận 8',
      'Quận 9',
      'Quận 10',
      'Quận 11',
      'Quận 12',
      'Quận Bình Tân',
      'Quận Bình Thạnh',
      'Quận Gò Vấp',
      'Quận Phú Nhuận',
      'Quận Tân Bình',
      'Quận Tân Phú',
      'Quận Thủ Đức',
      'Huyện Bình Chánh',
      'Huyện Cần Giờ',
      'Huyện Củ Chi',
      'Huyện Hóc Môn',
      'Huyện Nhà Bè',
    ],
    'Trà Vinh': [
      'Trà Vinh',
      'Càng Long',
      'Cầu Kè',
      'Tiểu Cần',
      'Châu Thành',
      'Cầu Ngang',
      'Trà Cú',
      'Duyên Hải',
    ],
    'Tuyên Quang': [
      'Tuyên Quang',
      'Sơn Dương',
      'Lâm Bình',
      'Na Hang',
      'Chiêm Hóa',
      'Hàm Yên',
      'Yên Sơn',
    ],
    'Vĩnh Long': [
      'Vĩnh Long',
      'Long Hồ',
      'Mang Thít',
      'Bình Minh',
      'Trà Ôn',
      'Vũng Liêm',
      'Tam Bình',
      'Bình Tân',
    ],
    'Vĩnh Phúc': [
      'Vĩnh Yên',
      'Phúc Yên',
      'Lập Thạch',
      'Tam Đảo',
      'Tam Dương',
      'Bình Xuyên',
      'Yên Lạc',
      'Vĩnh Tường',
    ],
    'Yên Bái': [
      'Yên Bái',
      'Nghĩa Lộ',
      'Lục Yên',
      'Văn Yên',
      'Mù Cang Chải',
      'Trạm Tấu',
      'Trấn Yên',
      'Văn Chấn',
      'Yên Bình',
    ],
  };
}
